### ISSUE TITLE
Sample data included in output

### ISSUE THREAD

**Issue by marksyzm** [1fabiopereira/react-native-pitch-detector#12]
This would easily double as a recordable package so that anyone who uses the pitch data can also go over the recording. I did the recording side here on this:
https://www.npmjs.com/package/react-native-microphone-stream

And wondered if you minded either including the changes or me providing a PR to implement it?

**Comment by marksyzm** [comment]
It also needs to make use of the certainty/accuracy data to be really useful. A lot of the time the pitch isn't accurate, so it likely needs that output also, usually on a factor of 0..1?

**Comment by 1fabiopereira** [comment]
I don't see a problem with implementing the buffer return along with the detection results, but I believe this should be an optional feature where whoever is using the lib can enable/disable it through configs. Feel free to send a PR.

About the accuracy, this is already on my roadmap, and I believe I will soon make this improvement available.

**Comment by marksyzm** [comment]
Thanks so much! I agree, make it optional. 
I need the android version more than anything at the moment - I'm running pitchy.js in the JS thread which runs amazingly on iOS but terribly on android, so I'll put that in a PR. I'll separate the 2 changes also. 

The iOS version looks a lot more difficult to implement either of those features from a glance at the code - I don't think Beethoven has proper accuracy data? Hard to tell as I can only see a threshold error end point.

**Comment by 1fabiopereira** [comment]
In addition to Beethoven, would there be another native lib that we could use? If we find that the accuracy is not adequate, we can compare with others and replace them if necessary. But for that we need to make sure that the gains will be significant, or even keep both and whoever is going to use it chooses which one to use.

**Comment by marksyzm** [comment]
Not native, but I’m very sure you could transform this library if you can find something that does FFT on iOS:

https://www.npmjs.com/package/pitchy

There's not a massive amount of logic to untangle. OR you could just have a microphone handler which sends the buffer like mine does, and run this library (pitchy) on the UI thread using something like reanimated's `worklet`s.

**Comment by marksyzm** [comment]
I'm running it on iPhone 14 pro with buffer length of 512

**Comment by marksyzm** [comment]
How about this for the FFT? https://superpowered.com/fft-and-polar-fft

Then it's a matter of transforming this to work with swift:
https://github.com/ianprime0509/pitchy/blob/main/index.js

**Comment by marksyzm** [comment]
In fact, this is better:
https://developer.apple.com/documentation/accelerate/fast_fourier_transforms

**Comment by 1fabiopereira** [comment]
I see the addition of FFT for iOS pitch detection as an improvement, leaving the Beethoven lib and the detection algorithms they provide. We can create another issue to discuss this.

**Comment by marksyzm** [comment]
Okay, I'll make that issue now.

**Comment by marksyzm** [comment]
I'm making a start on this this weekend as I need the functionality, if that's okay? I hope to also add in allowing the user to change audio input format so it turns noise cancellation off / on or any other features in the lists of constants provided for those.

**Comment by 1fabiopereira** [comment]
No problem, I'm off due to lack of time, but as soon as possible I'll be back to help with these implementations

**Comment by marksyzm** [comment]
It looks like I just need to add a custom signal tracker for input so that the microphone can be configured. My plan is to create an endpoint that collects the most current pitch data in the sample data output and emit that if the sample data is enabled. This would allow a user to collect that data and store the recording as a wave file, and at the same time be able to determine if pitch data exists currently. 

Here's a use case example app: https://apps.apple.com/us/app/onpitch-vocal-pitch-monitor/id1212118228

**Comment by marksyzm** [comment]
Ah, just had a proper read through the input signal tracker. Am I right in thinking that it picks up the audio input that is currently active if it already exists? I might try this as is with the present plugin to see if data pulls in from what you've set up already:
https://github.com/vadymmarkov/Beethoven/blob/master/Source/SignalTracking/Units/InputSignalTracker.swift

**Comment by marksyzm** [comment]
And are you using 2.4 of TarsosDSP? I'm guessing so, given he's dropped android again in the latest (2.5 - minor!) release

**Comment by marksyzm** [comment]
Small hiatus from working on my app, and I'm back to test this out. I've run the same steps, with permissions all set up in the podfile, but it seems pretty clear that it doesn't like the microphone of the pitch detector to run concurrently with the application. I'll investigate putting a signal tracker together for iOS and wrapping something up for TarsosDSP at some stage, but do you have any ideas why it won't run with my `react-native-microphone-stream` module? This would be a great help, thanks

**Comment by marksyzm** [comment]
Ah, it's not the combination of microphones running - it's this line in Beethoven's signal tracker:

```swift
let audioCaptureInput = try AVCaptureDeviceInput(device: audioDevice!)
```

Error:
> Thread 21: Fatal error: Unexpectedly found nil while unwrapping an Optional value

Optional binding seems to be required or something? Apparently `AVCaptureDeviceInput` also will crash the simulator and only work on a real device?

**Comment by marksyzm** [comment]
Okay, I can confirm that this no longer is an issue as it definitely runs in unison with the microphone plugins that I've tested so far. The bug with the simulator still exists, so I will have to contribute an updated Signal Tracker that's simulator friendly at some stage.

**Comment by marksyzm** [comment]
Okay, just need to fall back to AVAudioRecorder while running on simulator it turns out. I'll make an update for that at some point.
