### ISSUE TITLE
Implement accuracy value to provide in event listener

### ISSUE THREAD

**Issue by marksyzm** [1fabiopereira/react-native-pitch-detector#13]
Idea to implement apple's FFT into beethoven

This would be needed first before work on sending optional buffer data in the other issue (#12).

**Comment by 1fabiopereira** [comment]
I think that we can extend Beethoven library adding a FFT as new strategy.

📝 -  https://github.com/vadymmarkov/Beethoven#transform

It's make a sense for you @marksyzm?

**Comment by marksyzm** [comment]
Looking at it, yes. It implements all the different strategies for pitch matching already, and that wouldn't be fun requiring those.

**Comment by marksyzm** [comment]
Do you have an idea of how it can get accuracy detail from Beethoven? I can't see much in there from a good look through.

**Comment by marksyzm** [comment]
I've found also that others call it clarity, but accuracy seems as good

**Comment by marksyzm** [comment]
I've been looking into this concept, and I think it's fine to use as is without having to output an accuracy. Rather than that, I would just suggest allowing a configurable threshold option to be put in, which I see you have already. I'll update where I'm up to with the buffer data output and possibly implement the option to configure threshold / accuracy in the same PR.
