### ISSUE TITLE
Can't build the release app on RN 0.72

### ISSUE THREAD

**Issue by raphaelssampaio** [1fabiopereira/react-native-pitch-detector#30]
I tried to run the app with RN 0.72 and I couldn't. There's a problem with jtransc:jtransc-rt:0.6.7. So I went to android/build.gradle and I removed the line 74 and then everything worked as expected and I built the release apk.

**Comment by 1fabiopereira** [comment]
I'll check this out.

**Comment by 1fabiopereira** [comment]
Merged #31
