### ISSUE TITLE
no permission handler detected

### ISSUE THREAD

**Issue by derekhdawson** [1fabiopereira/react-native-pitch-detector#34]
Hi can anyone help me on this issue?

I'm trying to use this library using expo development builds and testing with expo go. Is it possible to address this problem without having to eject my expo app? Thanks

![IMG_3695](https://github.com/1fabiopereira/react-native-pitch-detector/assets/8495483/ee8dc0c6-d2c4-4579-99b6-a4397b67b861)

**Comment by marksyzm** [comment]
Hey, you just need to delete the pods directory in ios, plus the build directory, then run it again. If that's not working, you need to install the permissions checking stuff from here: 
https://1fabiopereira.github.io/react-native-pitch-detector/docs/usage#permissions

**Comment by derekhdawson** [comment]
In Expo you don't have access to the Pods directory, unless you delete eject. It's okay I created my own repo for this, closing now

**Comment by marksyzm** [comment]
Ah, yes you need to do prebuild in expo to do that. I definitely have this working in expo using that method. RN now recommend expo over their own custom rig!

**Comment by iamjoshua** [comment]
Even with prebuild in expo I can't seem to get this working. Was there some additional step that you haven't mentioned @marksyzm ? I'm about to fork this library and rip out this rather strange dependency as expo is now rather standard and provides its own permission management. If it's straightforward enough I'll submit a pull request.
