### ISSUE TITLE
Simulator/Non-physical devices not supported

### ISSUE THREAD

**Issue by Josephaedan** [1fabiopereira/react-native-pitch-detector#42]
While testing the example project `/example`, I was unable to get this package to work while running a Simulator iPhone as a device. As an additional check, I ran the same example project on my actual device and it works properly. 

For anyone who may be experiencing issues with `react-native-pitch-detector` crashing on start, please check that it does not work for both the Simulator and your actual device.

Edit: Unfortunately it seems the issue is with Beethoven not working for simulator: https://github.com/vadymmarkov/Beethoven/issues/53

**Comment by 1fabiopereira** [comment]
@Josephaedan I will add this note to the documentation and README.md of the project.

**Comment by Josephaedan** [comment]
Thanks @1fabiopereira, closing this issue since the incompatibility is caused by the native modules, not this package.
